### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by laorange** [laorange/paper-assistant#5]
Todo list:
- [x] 启用/禁用"语法检查"的状态按钮
- [x] 新增拖拽排序图标 [(来自评论区)](https://www.bilibili.com/video/BV1ZG4y1N7oM/#reply152210013200)
- [x] 规范中文排版 [#7](https://github.com/laorange/paper-assistant/issues/7)
- [x] 将全角括号从全角字符集合中移出 [#8](https://github.com/laorange/paper-assistant/issues/8)
- [x] 调整“标点符号后添加空格”功能效果 [#8 comment](https://github.com/laorange/paper-assistant/issues/8#issuecomment-1432508145)
- [x] 新增功能：去除引用标号（例如：<sup>[1]</sup>、<sup>[2, 3]</sup>、<sup>[4-7]</sup>）
- [x] 修复部分情况下不触发自动复制、自动清空

**Comment by laorange** [comment]
- [ ] 规范中文排版 [#7](https://github.com/laorange/paper-assistant/issues/7)

**Comment by laorange** [comment]
欢迎有兴趣一起开发的小伙伴直接提 PR ☺️ 我自己的开发进度会推到 `dev` 分支
